[package]
name = "motion_detection"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
mosquitto-client = "0.1.5"
bytes = "1"
image-compare = "0.2"
image = "0.24"
