[package]
name = "motion_detection"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1"
reqwest = { version = "0.11", features = ["blocking"] }
rumqttc = "0.20"
image-compare = "0.2"
image = "0.24"
